FROM docker.io/golang:1.24.3 AS builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon
ENV GOMAXPROCS=16

RUN git clone -b main https://github.com/k8snetworkplumbingwg/linuxptp-daemon.git  /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon && \
    cd /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon && \
    git rev-parse HEAD > /tmp/COMMIT_HASH

RUN make clean && make -j 16

FROM quay.io/centos/centos:stream9

ARG COMMIT_HASH
RUN yum install -y gpsd-minimal glibc gpsd-minimal-clients linuxptp ethtool hwdata synce4l  && yum clean all

# Create symlinks for executables to match references
RUN ln -s /usr/bin/gpspipe /usr/local/bin/gpspipe
RUN ln -s /usr/sbin/gpsd /usr/local/sbin/gpsd
RUN ln -s /usr/bin/ubxtool /usr/local/bin/ubxtool

COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon/bin/ptp /usr/local/bin/
COPY --from=builder /tmp/COMMIT_HASH /tmp/COMMIT_HASH

# If COMMIT_HASH not provided as build-arg, read it from the file
RUN if [ -z "$COMMIT_HASH" ]; then COMMIT_HASH=$(cat /tmp/COMMIT_HASH); fi && \
    echo "Commit: $COMMIT_HASH"

LABEL io.openshift.build.commit.url="https://github.com/k8snetworkplumbingwg/linuxptp-daemon/commit/${COMMIT_HASH:-unknown}"

CMD ["/usr/local/bin/ptp"]