FROM docker.io/golang:1.24.3 AS builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/ptp-operator
COPY .. .
ENV GO111MODULE=off
ENV GOMAXPROCS=16

RUN make -j 16

FROM quay.io/centos/centos:stream9

ARG COMMIT_HASH=unknown
ARG GIT_REMOTE_URL=https://github.com/k8snetworkplumbingwg/ptp-operator

COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/ptp-operator/build/_output/bin/ptp-operator /usr/local/bin/
COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/ptp-operator/manifests /manifests
COPY bindata /bindata

RUN echo "Built from commit: ${COMMIT_HASH} at ${GIT_REMOTE_URL}"

LABEL io.k8s.display-name="OpenShift ptp-operator" \
      io.k8s.description="This is a component that manages cluster PTP configuration." \
      io.openshift.tags="openshift,ptp" \
      io.openshift.build.commit.url="${GIT_REMOTE_URL}/commit/${COMMIT_HASH}" \
      com.redhat.delivery.appregistry=true \
      maintainer="PTP Dev Team <ptp-dev@redhat.com>"

ENTRYPOINT ["/usr/local/bin/ptp-operator"]
